# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cedadev/centos6"
  config.vm.synced_folder "C:/vagrant-shares/centos6-jaspy", "/vagrant-share", type: "nfs"
  config.vm.network "private_network", ip: "192.168.50.65"
  
# copy the root key
config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh
SHELL

end