# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Increased memory (default: 512) to resolve conda envs in jaspy (21/06/2019)
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end

  config.vm.box = "cedadev/centos7"
  config.vm.box_version = "0.0.1"
  config.vm.synced_folder "C:/vagrant-shares/general", "/vagrant-share", type: "nfs"
  config.vm.network "private_network", ip: "192.168.50.65"
  
# copy the root key
config.vm.provision :shell, inline: <<SHELL
set -x
mkdir -p /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh
yum install -y git

echo "[user]" > /home/vagrant/.gitconfig
echo "        name = Ag Stephens" >> /home/vagrant/.gitconfig
echo "        email = ag.stephens@stfc.ac.uk" >> /home/vagrant/.gitconfig
chown vagrant.vagrant /home/vagrant/.gitconfig

cp /home/vagrant/.gitconfig /root/.gitconfig
SHELL

end
